#!/usr/bin/env python3
"""Scaffold a frontend feature module using the DDD-oriented template."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path


NAME_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")


@dataclass
class GeneratedFile:
    path: Path
    content: str


def normalize_name(raw: str, label: str) -> str:
    value = raw.strip().lower()
    if not NAME_PATTERN.fullmatch(value):
        raise ValueError(
            f"{label} must match {NAME_PATTERN.pattern}; got {raw!r}"
        )
    return value


def to_pascal_case(value: str) -> str:
    parts = [part for part in re.split(r"[_\-]+", value) if part]
    return "".join(part[:1].upper() + part[1:] for part in parts)


def to_camel_case(value: str) -> str:
    pascal = to_pascal_case(value)
    return pascal[:1].lower() + pascal[1:] if pascal else pascal


def build_files(context: str, feature: str, root: Path) -> list[GeneratedFile]:
    feature_root = root / context / feature
    feature_name = to_pascal_case(feature)
    feature_camel = to_camel_case(feature)
    api_name = f"{feature_camel}Api"
    hook_name = f"use{feature_name}"
    panel_name = feature_name if feature_name.endswith("Panel") else f"{feature_name}Panel"
    types_name = f"{feature_name}Types"

    return [
        GeneratedFile(
            path=feature_root / "api" / f"{api_name}.ts",
            content=(
                f"export type {feature_name}ApiResponse = {{\n"
                "    status: string;\n"
                "};\n\n"
                f"export async function fetch{feature_name}(): Promise<{feature_name}ApiResponse> {{\n"
                "    return { status: \"TODO\" };\n"
                "}\n"
            ),
        ),
        GeneratedFile(
            path=feature_root / "model" / f"{types_name}.ts",
            content=(
                f"export type {feature_name}State = {{\n"
                "    status: string;\n"
                "};\n"
            ),
        ),
        GeneratedFile(
            path=feature_root / "hooks" / f"{hook_name}.ts",
            content=(
                "import { useMemo } from \"react\";\n"
                f"import type {{ {feature_name}State }} from \"../model/{types_name}\";\n\n"
                f"export function {hook_name}(state: {feature_name}State) {{\n"
                "    return useMemo(() => state.status, [state.status]);\n"
                "}\n"
            ),
        ),
        GeneratedFile(
            path=feature_root / "ui" / f"{panel_name}.tsx",
            content=(
                f"import type {{ {feature_name}State }} from \"../model/{types_name}\";\n\n"
                f"type {panel_name}Props = {{\n"
                f"    state: {feature_name}State;\n"
                "};\n\n"
                f"export function {panel_name}({{ state }}: {panel_name}Props) {{\n"
                "    return <section>{state.status}</section>;\n"
                "}\n"
            ),
        ),
        GeneratedFile(
            path=feature_root / "index.ts",
            content=(
                f"export * from \"./api/{api_name}\";\n"
                f"export * from \"./model/{types_name}\";\n"
                f"export * from \"./hooks/{hook_name}\";\n"
                f"export * from \"./ui/{panel_name}\";\n"
            ),
        ),
        GeneratedFile(
            path=feature_root / "README.md",
            content=(
                f"# {feature_name} Feature\n\n"
                "Generated by `scripts/scaffold_frontend_feature.py`.\n\n"
                "Rules:\n"
                "- Keep route composition in pages.\n"
                "- Keep API/state/view logic inside this feature.\n"
            ),
        ),
    ]


def write_output(payload: dict, output_json: str | None) -> None:
    lines = [
        "frontend_feature_scaffold",
        f"status={payload['status']}",
        f"context={payload['context']}",
        f"feature={payload['feature']}",
        f"dry_run={1 if payload['dry_run'] else 0}",
        f"created_count={payload['created_count']}",
        f"existing_count={payload['existing_count']}",
    ]
    for path in payload["existing_paths"]:
        lines.append(f"- existing={path}")
    for path in payload["created_paths"]:
        lines.append(f"- created={path}")
    if payload["status"] == "FAIL":
        lines.append("remediation=Use --force to overwrite, or delete conflicting files first.")
    else:
        lines.append("next_action=Integrate generated exports into page composition.")

    report = "\n".join(lines) + "\n"
    sys.stdout.write(report)

    if output_json:
        out = Path(output_json)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Scaffold frontend feature directories and starter files")
    parser.add_argument("--context", required=True, help="Context name (snake_case)")
    parser.add_argument("--feature", required=True, help="Feature name (snake_case)")
    parser.add_argument(
        "--root",
        default="frontend/src/features",
        help="Feature root directory",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print files that would be created")
    parser.add_argument("--force", action="store_true", help="Overwrite existing files")
    parser.add_argument("--output-json", help="Optional JSON report path")
    args = parser.parse_args()

    try:
        context = normalize_name(args.context, "context")
        feature = normalize_name(args.feature, "feature")
    except ValueError as exc:
        payload = {
            "status": "FAIL",
            "context": args.context,
            "feature": args.feature,
            "dry_run": args.dry_run,
            "created_count": 0,
            "created_paths": [],
            "existing_count": 0,
            "existing_paths": [],
            "error": str(exc),
        }
        write_output(payload=payload, output_json=args.output_json)
        return 1

    targets = build_files(context=context, feature=feature, root=Path(args.root))
    existing = [item.path for item in targets if item.path.exists()]
    if existing and not args.force:
        payload = {
            "status": "FAIL",
            "context": context,
            "feature": feature,
            "dry_run": args.dry_run,
            "created_count": 0,
            "created_paths": [],
            "existing_count": len(existing),
            "existing_paths": [path.as_posix() for path in existing],
        }
        write_output(payload=payload, output_json=args.output_json)
        return 1

    created: list[Path] = []
    if not args.dry_run:
        for item in targets:
            item.path.parent.mkdir(parents=True, exist_ok=True)
            item.path.write_text(item.content, encoding="utf-8", errors="strict")
            created.append(item.path)
    else:
        created = [item.path for item in targets]

    payload = {
        "status": "PASS",
        "context": context,
        "feature": feature,
        "dry_run": args.dry_run,
        "created_count": len(created),
        "created_paths": [path.as_posix() for path in created],
        "existing_count": len(existing),
        "existing_paths": [path.as_posix() for path in existing],
    }
    write_output(payload=payload, output_json=args.output_json)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
